export const iconNames = [
  "LuMedal",
  "LuTrees",
  "LuDollarSign",
  "LuBitcoin",
  "LuGlobe2",
  "LuApple",
  "LuSmilePlus",
  "LuStar",
  "LuGraduationCap",
  "LuUtensils",
  "LuUserPlus",
  "LuHeartPulse",
  "LuFlower",
  "LuHammer",
  "LuFootprints",
  "LuTestTubes",
  "LuPuzzle",
  "LuDiamond",
  "LuPaintbrush2",
  "LuShoppingCart",
  "LuLightbulb",
  "LuCalculator",
  "LuPersonStanding",
  "LuDumbbell",
  "LuPlane",
  "LuHeadphones",
  "LuHourglass",
  "LuBookOpen",
  "LuLeaf",
  "LuBanknote",
];

export const iconData = {
  "restaurant-outline": "LuUtensils",
  "medal-outline": "LuMedal",
  "leaf-outline": "LuTrees",
  "md-cash-outline": "LuBanknote",
  wifi: "LuWifi",
  "flask-outline": "LuTestTubes",
  "fitness-outline": "LuHeartPulse",
  "logo-bitcoin": "LuBitcoin",
  "earth-outline": "LuGlobe2",
  star: "LuStar",
  "nutrition-outline": "LuApple",
  "happy-outline": "LuSmilePlus",
  "school-outline": "LuGraduationCap",
  people: "LuUserPlus",
  "heart-outline": "LuHeartPulse",
  "flower-outline": "LuFlower",
  "hammer-outline": "LuHammer",
  "footsteps-outline": "LuFootprints",
  "extension-puzzle-outline": "LuPuzzle",
  "diamond-outline": "LuDiamond",
  "color-palette-outline": "LuPaintbrush2",
  "cart-outline": "LuShoppingCart",
  "bulb-outline": "LuLightbulb",
  "calculator-outline": "LuCalculator",
  "body-outline": "LuPersonStanding",
  "barbell-outline": "LuDumbbell",
  "airplane-outline": "LuPlane",
  "headset-outline": "LuHeadphones",
  "hourglass-outline": "LuHourglass",
  "book-outline": "LuBookOpen",
  "leaf-outline": "LuLeaf",
};
