import {
  LuUtensils,
  LuShoppingCart,
  LuDollarSign,
  LuMedal,
  LuTrees,
  LuTestTubes,
  LuApple,
  LuBitcoin,
  LuFlower,
  LuGlobe2,
  LuHeartPulse,
  LuPlane,
  LuSmilePlus,
  LuStar,
  LuWifi,
  LuGraduationCap,
  LuUserPlus,
  LuHammer,
  LuFootprints,
  LuPuzzle,
  LuDiamond,
  LuPaintbrush2,
  LuLightbulb,
  LuCalculator,
  LuPersonStanding,
  LuDumbbell,
  LuHeadphones,
  LuHourglass,
} from "react-icons/lu";
import { GiStrong } from "react-icons/gi";

export const iconNames = [
  "LuMedal",
  "LuTrees",
  "LuDollarSign",
  "GiStrong",
  "LuBitcoin",
  "LuGlobe2",
  "LuApple",
  "LuSmilePlus",
  "LuStar",
  "LuGraduationCap",
  "LuUtensils",
  "LuUserPlus",
  "LuHeartPulse",
  "LuFlower",
  "LuHammer",
  "LuFootprints",
  "LuTestTubes",
  "LuPuzzle",
  "LuDiamond",
  "LuPaintbrush2",
  "LuShoppingCart",
  "LuLightbulb",
  "LuCalculator",
  "LuPersonStanding",
  "LuDumbbell",
  "LuPlane",
  "LuHeadphones",
  "LuHourglass",
];

export const iconData = {
  "restaurant-outline": "LuUtensils",
  "medal-outline": "LuMedal",
  "leaf-outline": "LuTrees",
  "logo-usd": "LuDollarSign",
  wifi: "LuWifi",
  "flask-outline": "LuTestTubes",
  "fitness-outline": "GiStrong",
  "logo-bitcoin": "LuBitcoin",
  "earth-outline": "LuGlobe2",
  star: "LuStar",
  "nutrition-outline": "LuApple",
  "happy-outline": "LuSmilePlus",
  "school-outline": "LuGraduationCap",
  people: "LuUserPlus",
  "heart-outline": "LuHeartPulse",
  "flower-outline": "LuFlower",
  "hammer-outline": "LuHammer",
  "footsteps-outline": "LuFootprints",
  "extension-puzzle-outline": "LuPuzzle",
  "diamond-outline": "LuDiamond",
  "color-palette-outline": "LuPaintbrush2",
  "cart-outline": "LuShoppingCart",
  "bulb-outline": "LuLightbulb",
  "calculator-outline": "LuCalculator",
  "body-outline": "LuPersonStanding",
  "barbell-outline": "LuDumbbell",
  "airplane-outline": "LuPlane",
  "headset-outline": "LuHeadphones",
  "hourglass-outline": "LuHourglass",
};
